apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-deployment
  labels:
    app: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: eligetipavankumar/n8n:20
          ports:
            - containerPort: 5678
          env:
            - name: N8N_HOST
              value: "192.168.49.2"   # your minikube ip
            - name: N8N_PORT
              value: "5678"
            - name: N8N_PROTOCOL
              value: "http"
            - name: WEBHOOK_TUNNEL_URL
              value: "http://192.168.49.2:5678"
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "true"
            - name: N8N_BASIC_AUTH_USER
              value: "admin"
            - name: N8N_BASIC_AUTH_PASSWORD
              value: "admin123"
            - name: GENERIC_TIMEZONE
              value: "UTC"
            - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
              value: "true"
            - name: DB_SQLITE_POOL_SIZE
              value: "1"
            - name: N8N_RUNNERS_ENABLED
              value: "true"
